export const DEED_TYPES = [
  'Warranty Deed',
  'Warranty Deed w/ Vendors Lien',
  'Quitclaim Deed',
  'Deed',
  'Corrective Deed',
  'Grant Deed',
  'Bargain and Sale',
  'Tax Deed/Muni Deed',
  "Sheriff's Deed",
  'Foreclosure Deed',
  "Trustee's Deed",
  'Deed into Trust',
  'HOA/COA Foreclosure Deed',
  'Deed in Lieu of Foreclosure',
  "Executor's Deed",
  'Personal Rep. Deed',
  'Beneficiary Deed',
  'Deed of Purchase and Sale',
  'Assignment of Leasehold',
  'Inter-family Deed',
  'Outsale Deed',
  'Affidavit of Heirship',
  'Affidavit',
  'Other',
];

export const VESTING_STATUSES = [
  'Husband and Wife',
  'Wife and Husband',
  'Married',
  'Both Married',
  'Single',
  'A single man',
  'A single woman',
  'A single person',
  'Both Single',
  'Divorced',
  'Widow',
  'Unmarried man',
  'Unmarried woman',
  'Joint Tenants',
  'Husband and Wife, as Joint Tenants',
  'Joint Tenants with Right of Survivorship',
];

export const MORTGAGE_TYPES = [
  'Deed of Trust',
  'Mortgage',
  'Open-End Mortgage (or DoT)',
  'Closed-End Mortgage (or DoT)',
  'Credit Line Deed of Trust',
  "Vendor's Lien",
  'Purchase Money Mortgage (or DOT)',
  'Credit Line (Open ended)',
  'Fixed (Close ended)',
  'HELOC',
  'Contract for Deed',
  'Land Contract',
  'Tax Mortgage',
  'Tax Certificate/Lien',
  'Reverse Mortgage (or DoT)',
  'Lost Mortgage Affidavit',
  'Mortgage Deed',
  'Security Deed',
  'Deed to Secure Debt',
  'Subordinate Mortgage (or DOT)',
  'Partial Claim Mortgage (or DOT)',
  'Community Loan (or Forgivable Loan)',
  'Bond',
  'UCC',
  'Other',
];
